#!/usr/bin/env python3
"""
Phase 1 Acceptance Verification Script (Fixed)
Validates synthetic data generated by the Return-Risk Intelligence Engine simulator against
the requirements defined in the Data Generation Strategy.

Usage:
    python scripts/verify_phase1.py --config config/simulation/world_a.yaml

Author: Risk ML Team
Date: 2026-09-06
"""

import argparse
import json
import sys
from pathlib import Path

# Ensure standard output and error support utf-8 across platforms
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")

import polars as pl
import yaml

# ----------------------------------------------------------------------
# Configuration & constants
# ----------------------------------------------------------------------
RAW_DIR = Path("data/raw")
GROUND_TRUTH_DIR = Path("data/ground_truth")

REQUIRED_RAW_FILES = [
    "users.parquet",
    "products.parquet",
    "sellers.parquet",
    "orders.parquet",
    "returns.parquet",
    "events.parquet",
    "relationships.parquet",
]
GROUND_TRUTH_FILE = "hidden_labels.parquet"

EXPECTED_EVENT_TYPES = {
    "ACCOUNT_CREATED",
    "BROWSE",
    "ADD_TO_CART",
    "PURCHASE",
    "PAYMENT",
    "ORDER_CANCELLED",
    "ORDER_SHIPPED",
    "ORDER_DELIVERED",
    "DELIVERY_DELAY",
    "RETURN_REQUESTED",
    "RETURN_PICKED_UP",
    "RETURN_RECEIVED",
    "RETURN_REJECTED",
    "REFUND_ISSUED",
    "DEVICE_CHANGED",
    "ADDRESS_CHANGED",
    "PAYMENT_METHOD_CHANGED",
}

EXPECTED_FRAUD_FAMILIES = {
    "serial_return_abuse",
    "multi_account_abuse",
    "wardrobing",
}
EXPECTED_DIFFICULTIES = {"easy", "moderate", "stealthy"}


# ----------------------------------------------------------------------
# Utility functions
# ----------------------------------------------------------------------
def load_parquet(path):
    """Load a Parquet file and return Polars DataFrame if exists."""
    if not path.exists():
        print(f"[ERROR] File not found: {path}")
        return None
    return pl.read_parquet(path)


def check(condition, pass_msg, fail_msg, failures):
    """Record a check result."""
    if condition:
        print(f"[PASS] {pass_msg}")
        return True
    else:
        print(f"[FAIL] {fail_msg}")
        failures.append(fail_msg)
        return False


def any_none(*dfs):
    """Return True if any dataframe is None."""
    return any(df is None for df in dfs)


def extract_transaction_id(events_df):
    """
    Extract transaction_id from the events DataFrame.
    The events schema may store transaction_id either as a direct column
    or inside the entity_ids field (struct, JSON string, or python dict string).
    """
    if "transaction_id" in events_df.columns:
        return events_df

    if "order_id" in events_df.columns:
        return events_df.with_columns(pl.col("order_id").alias("transaction_id"))

    # Try struct field extraction
    try:
        if isinstance(events_df.schema.get("entity_ids"), pl.Struct):
            fields = [f.name for f in events_df.schema["entity_ids"].fields]
            if "transaction_id" in fields:
                return events_df.with_columns(
                    pl.col("entity_ids").struct.field("transaction_id").alias("transaction_id")
                )
            elif "order_id" in fields:
                return events_df.with_columns(
                    pl.col("entity_ids").struct.field("order_id").alias("transaction_id")
                )
    except Exception:
        pass

    # Try regex extraction for string entity_ids (handles both JSON and python dict strings)
    try:
        extracted = events_df.with_columns(
            pl.col("entity_ids")
            .str.extract(r"""['"](?:transaction_id|order_id)['"]\s*:\s*['"]?([a-zA-Z0-9_-]+)""", 1)
            .alias("transaction_id")
        )
        if extracted.filter(pl.col("transaction_id").is_not_null()).shape[0] > 0:
            return extracted
    except Exception:
        pass

    # Try JSON string extraction
    try:
        extracted = events_df.with_columns(
            pl.coalesce(
                pl.col("entity_ids").str.json_extract(dtype=pl.String, query_path="$.transaction_id"),
                pl.col("entity_ids").str.json_extract(dtype=pl.String, query_path="$.order_id"),
            ).alias("transaction_id")
        )
        if extracted.filter(pl.col("transaction_id").is_not_null()).shape[0] > 0:
            return extracted
    except Exception:
        pass

    # If all fail, return original (may cause join errors later, but validation will catch)
    print("[WARN] Could not extract transaction_id from events; delivery-before-return check may fail.")
    return events_df


def load_config(config_path):
    """Load simulation config YAML."""
    with open(config_path, "r") as f:
        return yaml.safe_load(f)


# ----------------------------------------------------------------------
# Individual validation functions
# ----------------------------------------------------------------------
def validate_file_existence(failures):
    print("\n=== Structural Validation: File Existence ===")
    all_exist = True
    for f in REQUIRED_RAW_FILES:
        p = RAW_DIR / f
        if not p.exists():
            print(f"[FAIL] Missing raw file: {p}")
            failures.append(f"Missing raw file: {f}")
            all_exist = False
    if not (GROUND_TRUTH_DIR / GROUND_TRUTH_FILE).exists():
        print(f"[FAIL] Missing ground truth file: {GROUND_TRUTH_DIR / GROUND_TRUTH_FILE}")
        failures.append("Missing ground truth file")
        all_exist = False
    else:
        print("[PASS] All raw and ground truth files present.")
    return all_exist


def validate_schemas(failures):
    print("\n=== Structural Validation: Schemas ===")
    schema_checks = {
        "users": ["user_id", "account_age_days", "segment", "region",
                  "purchase_propensity", "return_propensity", "fraud_propensity"],
        "products": ["product_id", "category", "price", "cogs", "shipping_cost",
                     "return_shipping_cost", "handling_cost", "restocking_cost",
                     "salvage_value_percentage"],
        "sellers": ["seller_id", "quality_score", "fulfillment_performance", "age_days"],
        "orders": ["transaction_id", "user_id", "product_id", "seller_id", "timestamp",
                   "price", "payment_id", "device_id", "address_id"],
        "returns": ["return_id", "transaction_id", "request_time", "reason", "condition",
                    "refund_amount", "days_to_return", "inspection_result",
                    "logistics_costs", "salvage_value"],
        "events": ["event_id", "timestamp", "event_type", "actor_id", "entity_ids", "payload"],
        "relationships": ["user_id", "entity_type", "entity_id", "first_seen", "last_seen"],
    }
    passed = True
    for table, required_cols in schema_checks.items():
        df = load_parquet(RAW_DIR / f"{table}.parquet")
        if df is None:
            check(False, "", f"Could not load {table} schema", failures)
            passed = False
            continue
        missing = set(required_cols) - set(df.columns)
        if missing:
            check(False, "", f"{table} missing columns: {missing}", failures)
            passed = False
        else:
            print(f"[PASS] {table} schema contains all required fields.")
    gt = load_parquet(GROUND_TRUTH_DIR / GROUND_TRUTH_FILE)
    if gt is not None:
        required_gt = {"return_id", "is_fraud", "true_scenario", "difficulty"}
        missing_gt = required_gt - set(gt.columns)
        if missing_gt:
            check(False, "", f"Ground truth missing columns: {missing_gt}", failures)
            passed = False
        else:
            print("[PASS] Ground truth schema contains all required fields.")
    else:
        check(False, "", "Ground truth file could not be loaded", failures)
        passed = False
    return passed


def validate_primary_keys(failures):
    print("\n=== Structural Validation: Primary Key Uniqueness ===")
    pk_checks = {
        "users": "user_id",
        "products": "product_id",
        "sellers": "seller_id",
        "orders": "transaction_id",
        "returns": "return_id",
        "events": "event_id",
    }
    passed = True
    for table, pk in pk_checks.items():
        df = load_parquet(RAW_DIR / f"{table}.parquet")
        if df is None:
            check(False, "", f"Could not load {table} for PK check", failures)
            passed = False
            continue
        total = len(df)
        unique = df[pk].n_unique()
        if total != unique:
            check(False, "", f"{table}.{pk} not unique: {total} rows but {unique} unique values", failures)
            passed = False
        else:
            print(f"[PASS] {table}.{pk} unique ({unique} rows).")
    return passed


def validate_foreign_keys(failures):
    print("\n=== Structural Validation: Foreign Key Integrity ===")
    users = load_parquet(RAW_DIR / "users.parquet")
    products = load_parquet(RAW_DIR / "products.parquet")
    sellers = load_parquet(RAW_DIR / "sellers.parquet")
    orders = load_parquet(RAW_DIR / "orders.parquet")
    returns = load_parquet(RAW_DIR / "returns.parquet")
    relationships = load_parquet(RAW_DIR / "relationships.parquet")

    if any_none(users, products, sellers, orders, returns, relationships):
        check(False, "", "Could not load all tables for FK check", failures)
        return False

    passed = True

    bad_user = orders.join(users, on="user_id", how="anti")
    if bad_user.is_empty():
        print("[PASS] orders.user_id all exist in users.")
    else:
        check(False, "", f"{len(bad_user)} orders have invalid user_id", failures)
        passed = False

    bad_prod = orders.join(products, on="product_id", how="anti")
    if bad_prod.is_empty():
        print("[PASS] orders.product_id all exist in products.")
    else:
        check(False, "", f"{len(bad_prod)} orders have invalid product_id", failures)
        passed = False

    bad_seller = orders.join(sellers, on="seller_id", how="anti")
    if bad_seller.is_empty():
        print("[PASS] orders.seller_id all exist in sellers.")
    else:
        check(False, "", f"{len(bad_seller)} orders have invalid seller_id", failures)
        passed = False

    bad_txn = returns.join(orders, on="transaction_id", how="anti")
    if bad_txn.is_empty():
        print("[PASS] returns.transaction_id all exist in orders.")
    else:
        check(False, "", f"{len(bad_txn)} returns have invalid transaction_id", failures)
        passed = False

    bad_rel = relationships.join(users, on="user_id", how="anti")
    if bad_rel.is_empty():
        print("[PASS] relationships.user_id all exist in users.")
    else:
        check(False, "", f"{len(bad_rel)} relationships have invalid user_id", failures)
        passed = False

    return passed


def validate_business_constraints(failures):
    print("\n=== Business Constraint Validation ===")
    orders = load_parquet(RAW_DIR / "orders.parquet")
    returns = load_parquet(RAW_DIR / "returns.parquet")
    events = load_parquet(RAW_DIR / "events.parquet")
    relationships = load_parquet(RAW_DIR / "relationships.parquet")
    users = load_parquet(RAW_DIR / "users.parquet")

    if any_none(orders, returns, events, relationships, users):
        check(False, "", "Could not load all tables for business constraint checks", failures)
        return False

    passed = True

    # 1. Refund amount <= order amount
    joined = returns.join(orders, on="transaction_id", how="inner", suffix="_order")
    bad_amount = joined.filter(pl.col("refund_amount") > pl.col("price"))
    if bad_amount.is_empty():
        print("[PASS] All refund_amount <= order price.")
    else:
        check(False, "", f"{len(bad_amount)} returns have refund > order amount", failures)
        passed = False

    # 2. days_to_return >= 0
    bad_days = returns.filter(pl.col("days_to_return") < 0)
    if bad_days.is_empty():
        print("[PASS] All days_to_return >= 0.")
    else:
        check(False, "", f"{len(bad_days)} returns have negative days_to_return", failures)
        passed = False

    # 3. Return after delivery
    deliveries = events.filter(pl.col("event_type") == "ORDER_DELIVERED")
    if not deliveries.is_empty():
        deliveries = extract_transaction_id(deliveries)  # ensure transaction_id present
        ret_del = returns.join(deliveries, on="transaction_id", how="inner", suffix="_delivery")
        bad_timing = ret_del.filter(pl.col("request_time") < pl.col("timestamp"))
        if bad_timing.is_empty():
            print("[PASS] All returns occur after delivery (if delivery event exists).")
        else:
            check(False, "", f"{len(bad_timing)} returns requested before delivery", failures)
            passed = False
    else:
        print("[WARN] No ORDER_DELIVERED events found. Cannot verify delivery-before-return.")

    # 4. Relationship first_seen <= last_seen
    bad_rel_time = relationships.filter(pl.col("first_seen") > pl.col("last_seen"))
    if bad_rel_time.is_empty():
        print("[PASS] Relationship first_seen <= last_seen.")
    else:
        check(False, "", f"{len(bad_rel_time)} relationships have first_seen > last_seen", failures)
        passed = False

    # 5. Account age >= 0
    bad_age = users.filter(pl.col("account_age_days") < 0)
    if bad_age.is_empty():
        print("[PASS] All account_age_days >= 0.")
    else:
        check(False, "", f"{len(bad_age)} users have negative account_age_days", failures)
        passed = False

    return passed


def validate_distribution_plausibility(failures):
    print("\n=== Distribution Plausibility ===")
    users = load_parquet(RAW_DIR / "users.parquet")
    products = load_parquet(RAW_DIR / "products.parquet")
    orders = load_parquet(RAW_DIR / "orders.parquet")
    returns = load_parquet(RAW_DIR / "returns.parquet")

    if any_none(users, products, orders, returns):
        check(False, "", "Could not load tables for distribution checks", failures)
        return False

    if products["price"].min() > 0:
        print("[PASS] Product prices positive.")
    else:
        check(False, "", "Found non-positive product price", failures)

    if returns["refund_amount"].min() >= 0:
        print("[PASS] Refund amounts non-negative.")
    else:
        check(False, "", "Negative refund amount", failures)

    cat_orders = orders.join(products.select(["product_id", "category"]), on="product_id").group_by("category").agg(pl.col("transaction_id").count().alias("orders"))
    cat_returns = returns.join(orders, on="transaction_id").join(products.select(["product_id", "category"]), on="product_id").group_by("category").agg(pl.col("return_id").count().alias("returns"))
    cat_stats = cat_orders.join(cat_returns, on="category", how="left").with_columns(
        (pl.col("returns") / pl.col("orders")).alias("return_rate")
    )
    if cat_stats["return_rate"].is_null().sum() == 0 and cat_stats["return_rate"].min() >= 0 and cat_stats["return_rate"].max() <= 1:
        print("[PASS] Category return rates within [0,1].")
    else:
        check(False, "", "Category return rates out of bounds", failures)
    return True


def validate_dependencies(failures):
    print("\n=== Dependency Validation ===")
    orders = load_parquet(RAW_DIR / "orders.parquet")
    returns = load_parquet(RAW_DIR / "returns.parquet")
    events = load_parquet(RAW_DIR / "events.parquet")
    products = load_parquet(RAW_DIR / "products.parquet")
    users = load_parquet(RAW_DIR / "users.parquet")

    if any_none(orders, returns, events, products, users):
        check(False, "", "Could not load tables for dependency checks", failures)
        return False

    prod_cat = products.select(["product_id", "category"])
    orders_cat = orders.join(prod_cat, on="product_id")
    returns_cat = returns.join(orders_cat, on="transaction_id")
    cat_return_rate = (
        orders_cat.group_by("category").agg(pl.col("transaction_id").count().alias("orders"))
        .join(
            returns_cat.group_by("category").agg(pl.col("return_id").count().alias("returns")),
            on="category",
            how="left",
        )
        .with_columns((pl.col("returns") / pl.col("orders")).alias("return_rate"))
    )
    print("Return rates by category:")
    print(cat_return_rate)

    deliveries = events.filter(pl.col("event_type") == "ORDER_DELIVERED")
    if deliveries.is_empty():
        print("[WARN] No delivery events to analyze delivery delay dependency.")
    else:
        deliveries = extract_transaction_id(deliveries)
        ret_del = returns.join(deliveries, on="transaction_id", how="inner").with_columns(
            (pl.col("request_time") - pl.col("timestamp")).dt.total_days().alias("delivery_delay_days")
        )
        ret_del = ret_del.with_columns(
            pl.when(pl.col("delivery_delay_days") <= 1).then(pl.lit("0-1d"))
            .when(pl.col("delivery_delay_days") <= 7).then(pl.lit("1-7d"))
            .when(pl.col("delivery_delay_days") <= 30).then(pl.lit("7-30d"))
            .otherwise(pl.lit(">30d"))
            .alias("delay_bucket")
        )
        delay_stats = ret_del.group_by("delay_bucket").agg(pl.col("return_id").count().alias("returns"))
        print("Return count by delivery delay bucket:")
        print(delay_stats)

    segment_stats = orders.join(users.select(["user_id", "segment"]), on="user_id").group_by("segment").agg(
        pl.col("price").mean().alias("avg_order_value"),
        pl.col("price").std().alias("std_order_value"),
    )
    print("Order value by segment:")
    print(segment_stats)

    return True


def validate_temporal_coherence(failures):
    print("\n=== Temporal Coherence ===")
    events = load_parquet(RAW_DIR / "events.parquet")
    if events is None:
        check(False, "", "Could not load events for temporal checks", failures)
        return False

    events_sorted = events.sort(["actor_id", "timestamp"]).with_columns(
        pl.col("timestamp").shift(1).over("actor_id").alias("prev_timestamp")
    )
    out_of_order = events_sorted.filter(pl.col("prev_timestamp") > pl.col("timestamp"))
    if out_of_order.is_empty():
        print("[PASS] Events are chronologically ordered per actor.")
    else:
        check(False, "", f"{len(out_of_order)} out-of-order events", failures)
        return False

    intervals = events_sorted.with_columns(
        (pl.col("timestamp") - pl.col("prev_timestamp")).dt.total_seconds().alias("interval_seconds")
    ).filter(~pl.col("interval_seconds").is_null())
    if intervals["interval_seconds"].std() > 0:
        print("[PASS] Inter-event intervals show variability.")
    else:
        check(False, "", "Inter-event intervals lack variability", failures)
        return False

    max_ts = events["timestamp"].max()
    print(f"Maximum event timestamp: {max_ts}")
    return True


def validate_behavioral_patterns(failures):
    print("\n=== Behavioral Validation ===")
    returns = load_parquet(RAW_DIR / "returns.parquet")
    orders = load_parquet(RAW_DIR / "orders.parquet")
    if any_none(returns, orders):
        check(False, "", "Could not load tables for behavioral checks", failures)
        return False

    ret_user = returns.join(orders.select(["transaction_id", "user_id"]), on="transaction_id")
    ret_count_per_user = ret_user.group_by("user_id").agg(pl.col("return_id").count().alias("total_returns"))
    if ret_count_per_user["total_returns"].max() > 1:
        print(f"[PASS] Some users have multiple returns; max per user = {ret_count_per_user['total_returns'].max()}.")
    else:
        print("[WARN] No repeat returns found; suspiciously low repeat behavior.")
    return True


def validate_graph_structure(failures):
    print("\n=== Graph Validation ===")
    relationships = load_parquet(RAW_DIR / "relationships.parquet")
    gt = load_parquet(GROUND_TRUTH_DIR / GROUND_TRUTH_FILE)
    orders_df = load_parquet(RAW_DIR / "orders.parquet")
    returns_df = load_parquet(RAW_DIR / "returns.parquet")

    if any_none(relationships, gt, orders_df, returns_df):
        check(False, "", "Could not load tables for graph validation", failures)
        return False

    for entity_type in ["device", "address", "payment"]:
        ent_df = relationships.filter(pl.col("entity_type") == entity_type)
        if ent_df.is_empty():
            print(f"[WARN] No relationships for entity type {entity_type}.")
            continue
        shared = ent_df.group_by("entity_id").agg(pl.col("user_id").n_unique().alias("num_users"))
        shared_count = shared.filter(pl.col("num_users") > 1).shape[0]
        print(f"[INFO] {entity_type}: {shared_count} entities shared by >1 user.")

    fraud_returns = gt.filter(pl.col("is_fraud") == True)["return_id"].to_list()
    fraud_txns = returns_df.filter(pl.col("return_id").is_in(fraud_returns))["transaction_id"].to_list()
    fraud_users = orders_df.filter(pl.col("transaction_id").is_in(fraud_txns))["user_id"].unique().to_list()
    fraud_relationships = relationships.filter(pl.col("user_id").is_in(fraud_users))
    shared_fraud_entities = fraud_relationships.group_by("entity_id").agg(pl.col("user_id").n_unique().alias("num_users")).filter(pl.col("num_users") > 1)
    if not shared_fraud_entities.is_empty():
        print(f"[PASS] Found {shared_fraud_entities.shape[0]} shared entities among fraud users (multi-account abuse likely present).")
    else:
        check(False, "", "No shared entities among fraud users; multi-account abuse missing.", failures)
        return False

    non_fraud_returns = gt.filter(pl.col("is_fraud") == False)["return_id"].to_list()
    legit_txns = returns_df.filter(pl.col("return_id").is_in(non_fraud_returns))["transaction_id"].to_list()
    legit_users = orders_df.filter(pl.col("transaction_id").is_in(legit_txns))["user_id"].unique().to_list()
    legit_relationships = relationships.filter(pl.col("user_id").is_in(legit_users))
    shared_legit_entities = legit_relationships.group_by("entity_id").agg(pl.col("user_id").n_unique().alias("num_users")).filter(pl.col("num_users") > 1)
    if not shared_legit_entities.is_empty():
        print(f"[PASS] Found {shared_legit_entities.shape[0]} shared entities among legitimate users (hard negatives present).")
    else:
        print("[WARN] No shared entities among legitimate users; consider adding family household patterns.")

    return True


def validate_fraud_scenario_coverage(failures):
    print("\n=== Fraud Scenario Coverage ===")
    gt = load_parquet(GROUND_TRUTH_DIR / GROUND_TRUTH_FILE)
    if gt is None:
        check(False, "", "Could not load ground truth", failures)
        return False
    fraud_rows = gt.filter(pl.col("is_fraud") == True)
    families = set(fraud_rows["true_scenario"].unique().to_list())
    missing_families = EXPECTED_FRAUD_FAMILIES - families
    if not missing_families:
        print("[PASS] All three fraud families present.")
    else:
        check(False, "", f"Missing fraud families: {missing_families}", failures)
        return False
    difficulties = set(fraud_rows["difficulty"].unique().to_list())
    missing_diffs = EXPECTED_DIFFICULTIES - difficulties
    if not missing_diffs:
        print("[PASS] All difficulty variants (easy, moderate, stealthy) present.")
    else:
        check(False, "", f"Missing difficulty variants: {missing_diffs}", failures)
        return False
    return True


def validate_leakage(failures):
    print("\n=== Leakage Check ===")
    hidden_cols = {"is_fraud", "true_scenario", "difficulty"}
    for f in REQUIRED_RAW_FILES:
        df = load_parquet(RAW_DIR / f)
        if df is not None:
            found = set(df.columns).intersection(hidden_cols)
            if found:
                check(False, "", f"{f} contains hidden columns {found}", failures)
                return False
    print("[PASS] No hidden label columns in raw tables.")
    return True


def validate_reproducibility_metadata(failures):
    print("\n=== Reproducibility Metadata ===")
    meta_file = Path("data") / "simulation_metadata.json"
    if not meta_file.exists():
        print("[WARN] No simulation_metadata.json found. Reproducibility not fully verifiable from data alone.")
        return True
    with open(meta_file, "r") as f:
        meta = json.load(f)
    required_keys = {"simulation_version", "config_version", "world_id", "random_seed", "generator_timestamp"}
    missing_keys = required_keys - set(meta.keys())
    if not missing_keys:
        print("[PASS] Simulation metadata includes version, world_id, seed, timestamp.")
    else:
        check(False, "", f"Missing metadata keys: {missing_keys}", failures)
        return False
    return True


# ----------------------------------------------------------------------
# Main orchestrator
# ----------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="Phase 1 Data Validation")
    parser.add_argument("--config", type=str, default="config/simulation/world_a.yaml",
                        help="Simulation config file path")
    args = parser.parse_args()

    config_path = Path(args.config)
    if not config_path.exists():
        print(f"[ERROR] Config file not found: {config_path}")
        sys.exit(1)
    config = load_config(config_path)
    print(f"Validating Phase 1 data for world_id={config.get('world_id')} seed={config.get('random_seed')}")

    failures = []

    if not validate_file_existence(failures):
        sys.exit(1)

    validate_schemas(failures)
    validate_primary_keys(failures)
    validate_foreign_keys(failures)
    validate_business_constraints(failures)
    validate_distribution_plausibility(failures)
    validate_dependencies(failures)
    validate_temporal_coherence(failures)
    validate_behavioral_patterns(failures)
    validate_graph_structure(failures)
    validate_fraud_scenario_coverage(failures)
    validate_leakage(failures)
    validate_reproducibility_metadata(failures)

    print("\n" + "=" * 60)
    print("VALIDATION SUMMARY")
    print("=" * 60)
    if failures:
        print(f"FAILED: {len(failures)} check(s) failed.")
        for f in failures:
            print(f"  - {f}")
        sys.exit(1)
    else:
        print("ALL CHECKS PASSED. Phase 1 data is acceptable.")
        sys.exit(0)


if __name__ == "__main__":
    main()